language: ruby
script: bundle exec rspec
sudo: false
rvm:
  - "2.4.9"
  - "2.5.7"
  - "2.6.5"
  - "2.7.0"

gemfile:
  - Gemfile
  - gemfiles/activerecord-5.0.gemfile
  - gemfiles/activerecord-5.1.gemfile
  - gemfiles/activerecord-6.0.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/activerecord-6.0.gemfile
      rvm: 2.4.9
